project_id: exp383
project_name: cell-x-strain-rnaseq
nfcore_rnaseq_version: 3.23.0
merged_reads_root: /media/tmurphy/4TB_HDD/exp383/merged_fastq
raw_reads_backup_root: /mnt/timeshift/rsync-backups/tmurphy/PRJ25147
multiqc_report: /home/tmurphy/exp383_code/cell-x-strain-rnaseq/MultiQC_Report_PRJ25147.html
metadata_csv: /home/tmurphy/exp383_code/cell-x-strain-rnaseq/metadata/25-04-07-EXP_383_FANS_SAMPLE_METADATA.csv
missing_samples_csv: /home/tmurphy/exp383_code/cell-x-strain-rnaseq/metadata/MISSING.csv
sample_level_samplesheet_csv: /home/tmurphy/exp383_code/cell-x-strain-rnaseq/metadata/exp383_nfcore_rnaseq_samplesheet_template.csv
batch_samplesheet_dir: /home/tmurphy/exp383_code/cell-x-strain-rnaseq/metadata/batches
samplesheet_csv: /home/tmurphy/exp383_code/cell-x-strain-rnaseq/metadata/exp383_nfcore_rnaseq_samplesheet_template.csv
samplesheet_status: merged_fastq_paths_populated
trimmer: fastp
remove_ribo_rna: true
ribo_removal_tool: bowtie2
ribo_database_manifest: /home/tmurphy/exp383_code/cell-x-strain-rnaseq/resources/rrna/eukaryote_rrna_manifest.txt
pseudo_aligner: salmon
skip_alignment: true
reference_source: ensembl
reference_release: 115
reference_assembly: GRCm39
default_results_dir: /media/tmurphy/4TB_HDD/exp383/nfcore_rnaseq
default_work_dir: /media/tmurphy/2TB_SSD/exp383/nfcore_rnaseq_work
